### PR TITLE
Created the contact page for issue EarWorms page

### PR DESCRIPTION
**Pull request by Basim03**
Created the contact form page for issue #29 please take a look @0silverback0 
Thank you!

### CODE REVIEW

**Comment by 0silverback0** [comment]
👏👏👏 nicely done! I appreciate your speed and communication as well.

**Comment by Basim03** [comment]
Thank you @0silverback0 looking forward for more contributions 😊

**Comment by 0silverback0** [comment]
@Basim03 are you on discord?

**Comment by Basim03** [comment]
Yes i am on discord

**Comment by 0silverback0** [comment]
Send me a message 0silverback0

**Pull request merged**
