### PR TITLE
Books store LandingPage

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
here is the Books_Store Landing Page ,

Which contains a beautiful navbar built using bootstrap and it contains
 **Home, Books , Add Books , Get all users , Requests , Logout**  as **Nav item Links** with Hovering effect and Nav bar is highlighted with an orange color at bottom

and body of this page contains a good animated , moving Background GIF and a Heading **Books Store for You** with  a small Bootstrap Btn  primary **View Books**  which has hovering effect al well

and this page also have Footer and **Footer** is also highlighted with a color;

Once go through this and merge it  _Hacktoberfest_23 : )

https://github.com/0silverback0/LandingPages/assets/127650446/4342dc35-e53d-4386-8c06-882287eb8dc3

### CODE REVIEW

**Comment by 0silverback0** [comment]
could you add a  link to the index.html file in the root directory for the home link on your page and a description to this PR

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I had added  link to the index.html file in the root directory for the home link for my Page 
and also , I had written a good description of this PR ;

once please check and merge it _Hacktoberfest-2023 : )

**Comment by 0silverback0** [comment]
i have added merged newr commits than the copy you provided, run git pull to get the latest copy of the repo then make your changes

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I had made a new PR with all updated once please check PR #20  _Hacktoberfest_2023 : )

**Comment by Bharath-KumarReddy** [comment]
once please check and merge it and inform incase of modifications _Hacktobefest_2023 : )

**Comment by 0silverback0** [comment]
your branch is not up to date. https://deploy-preview-16--radiant-cucurucho-b049fa.netlify.app/. The app currently looks like this https://radiant-cucurucho-b049fa.netlify.app/ please run git pull before your commit

**Comment by Bharath-KumarReddy** [comment]
Hi ,
Once kindly check I had updated my Index.html file and also I had changed my code you can see I made this With a commit message of **-m "Updated Books_Store_LandingPage"**

**Review by 0silverback0 — APPROVED** [review]
in the home tab of your site just link it back to /index.html. this just makes it easier for useres to navigate back to the other projects to view

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I just now **added a Link to Home tab** of my Books_store landing page , If user clicks on the Home link then he will be navigated to Main landing page that is **Welcome to Landing Pages Repo** 

once check the **commit Added link to Home Tab**  _Hacktoberfest_2023 : )

**Comment by 0silverback0** [comment]
Perfect! Merging now!

**Pull request merged**
