### PR TITLE
Fixed the issue #18 

### PR DESCRIPTION
**Pull request by Basim03**
Fixed issue #18 where the navbar was unresponsive for smaller devices @0silverback0 please do cross check and let me know if any changes are needed

Thanks!

### CODE REVIEW

**Comment by 0silverback0** [comment]
Your branch is behind main run a git pull to update then make your commit

**Comment by Basim03** [comment]
but it says my branch is 4 commits ahead of the main branch

**Comment by 0silverback0** [comment]
Got it now! And merged!

**Comment by Basim03** [comment]
Thank you @0silverback0

**Comment by 0silverback0** [comment]
no problem maybe we can collaborate again in the future

**Pull request merged**
