### PR TITLE
made the landing page responsive and improved the navbar

### LINKED ISSUE #38: Improve Design for mobile in Watch Landing page
titled Animated Landing page in the repo.  The nav isn't responsive here and  could be improved. Anyone want to have a shot at it?

### PR DESCRIPTION
**Pull request by harshvyas-22**
made necessary changes in the landing page so as to improve ui and make it beautiful .fixes #38

### CODE REVIEW

**Comment by harshvyas-22** [comment]
ready to listen future improvements

**Comment by 0silverback0** [comment]
looks like on small screens the watch images disappear since thats the main focal point of this site i think it would be better to keep that visible. also the button and the social links slam together on small screens as well. if you could please fix that i will merge! thanks

**Comment by harshvyas-22** [comment]
please have a look @0silverback0

**Comment by 0silverback0** [comment]
Awesome thanks!!

**Pull request merged**
