### PR TITLE
Added Portfolio Website

### PR DESCRIPTION
**Pull request by harshit1142**
Added My portfolio Responsive Website
Please Add Hacktoberfest Label...

### CODE REVIEW

**Comment by harshit1142** [comment]
Please add Hacktoberfest label too.

**Review by 0silverback0 — CHANGES_REQUESTED** [review]
Needs a link to the repo home page at /index.html for easy navigation

**Comment by harshit1142** [comment]
> Needs a link to the repo home page at /index.html for easy navigation

THIS LINE --> ./Portfolio_HP/index.html ?

**Comment by harshit1142** [comment]
> Needs a link to the repo home page at /index.html for easy navigation

OKAY , like back button

**Comment by harshit1142** [comment]
Done

**Pull request merged**
