### PR TITLE
add discord clone #88

### PR DESCRIPTION
**Pull request by KRRISHSINGH08**
Adding discord clone issue #88

### CODE REVIEW

**Comment by KRRISHSINGH08** [comment]
Hey, Please check and merge.

**Comment by KRRISHSINGH08** [comment]
Hey, please check and merge.

**Comment by 0silverback0** [comment]
theres an issue with your deploy preview. Im not sure whats going on just yet

**Comment by KRRISHSINGH08** [comment]
I tried deploying it on my github  and it's working totally fine. What is the issue here, Can you help with this?

**Pull request closed without merging**
