### PR TITLE
Added correct style in header image and made it responsive

### LINKED ISSUE #1: Fix header image
I want to moved and resize the header image so that the headphones are visible  but have the image retain the full with of the device. This should also fix the issue on all size devices

### PR DESCRIPTION
**Pull request by Harshsharmaa28**
fixes #1 
Made the Header image resposive and the issue of image resizing is also solved.

### CODE REVIEW

**Comment by 0silverback0** [comment]
Thanks ! This works as expected now on small screens all the way up to laptop sizes and I will merge and add hacktoberfest tags

**Comment by Harshsharmaa28** [comment]
It's ok if you have some paid work related to development feel to free to
connect I am open to work.

**Comment by 0silverback0** [comment]
Sorry I have no paid work im looking for that myself! But maybe we can collaborate on more projects together.

**Comment by Harshsharmaa28** [comment]
Ok, no problem

**Pull request merged**
